DELETE FROM public.inspirations;

INSERT INTO public.inspirations (category, image_url) VALUES ('Footwear', '/Assets/inspiration/Footwear/Luxury Shoes Packaging Boxes At Aqua Printers in USA.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Footwear', '/Assets/inspiration/Footwear/WhatsApp Image 2026-05-11 at 10.04.59 PM.jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Footwear', '/Assets/inspiration/Footwear/download.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Footwear', '/Assets/inspiration/Footwear/WhatsApp Image 2026-05-11 at 10.05.00 PM (1).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Footwear', '/Assets/inspiration/Footwear/Shoe Packaging - Shyamali Verma.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Footwear', '/Assets/inspiration/Footwear/126a8a882c9f84555428a30d02d29805.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Footwear', '/Assets/inspiration/Footwear/Home - hopa studio.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Footwear', '/Assets/inspiration/Footwear/0d839b7e5bdcb230c695169e9304b08a.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Footwear', '/Assets/inspiration/Footwear/17a221ec3e4d3202d419c0579fbac7d9.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Footwear', '/Assets/inspiration/Footwear/c1a643c2e9ea918f6ec6db350b0c558b.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Footwear', '/Assets/inspiration/Footwear/WhatsApp Image 2026-05-11 at 10.04.59 PM (2).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Footwear', '/Assets/inspiration/Footwear/82f3994f8b8e2d47d967a9edc7f25d45.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Footwear', '/Assets/inspiration/Footwear/This shoebox extends its lifecycle by serving a triple function_ as packaging, as a shoe carrier and as a storage box 👟 When we think about packaging, we want it to be designed in a way that can be reused, is made u.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Footwear', '/Assets/inspiration/Footwear/download (2).jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Accessories', '/Assets/inspiration/Accessories/0c8a6e198d66eb589eec0e037429da0b.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Accessories', '/Assets/inspiration/Accessories/1.jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Accessories', '/Assets/inspiration/Accessories/3.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Accessories', '/Assets/inspiration/Accessories/3e36b3f02ac621dd507729429666e094.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Accessories', '/Assets/inspiration/Accessories/3f2fda9654d1bf6e7fc72af9b6a48114.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Accessories', '/Assets/inspiration/Accessories/4.jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Accessories', '/Assets/inspiration/Accessories/4.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Accessories', '/Assets/inspiration/Accessories/950392c5f7c2f893b512d8e484212b01.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Accessories', '/Assets/inspiration/Accessories/WhatsApp Image 2026-05-11 at 10.04.54 PM (3).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Accessories', '/Assets/inspiration/Accessories/WhatsApp Image 2026-05-11 at 10.05.09 PM (1).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Accessories', '/Assets/inspiration/Accessories/c42b6527e4faf41f535f4f949d3897e8.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Accessories', '/Assets/inspiration/Accessories/f2f0d27a5c3cfd9a8015b5bbdc3eb2d0.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/17476356f5040d32880b3f53d19eceeb.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/ce808f2d96d86bf688eefd8576202723.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/WhatsApp Image 2026-05-11 at 10.04.54 PM (4).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/0f7ec9688af2ba983393bd431190f8f3.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/WhatsApp Image 2026-05-11 at 10.05.01 PM.jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/WhatsApp Image 2026-05-11 at 10.05.09 PM.jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/3e2cb1a035b0ce42d6ac2f4e72c68034.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/01fd51dcf302ba78c9c2b54df335b537.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/48f5722dcbdd92f42d561c849f3d2ee5.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/WhatsApp Image 2026-05-11 at 10.05.07 PM (2).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/WhatsApp Image 2026-05-11 at 10.04.57 PM.jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/WhatsApp Image 2026-05-11 at 10.04.56 PM.jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/IMG_0442.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/WhatsApp Image 2026-05-11 at 10.04.56 PM (1).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/62f2d063077bf8a14f947a684f1e8c6e.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/5d32013f39a1c89387601ae238f44084.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/WhatsApp Image 2026-05-11 at 10.05.07 PM (1).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/3fdc3d81486c587d4a3739c32e6562b7.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Food and Beverage', '/Assets/inspiration/F&B/WhatsApp Image 2026-05-11 at 10.04.56 PM (2).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Innovative', '/Assets/inspiration/Innovative/IMG_0438.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Innovative', '/Assets/inspiration/Innovative/IMG_0439.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Innovative', '/Assets/inspiration/Innovative/IMG_0449.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Innovative', '/Assets/inspiration/Innovative/60435b57c517d1655d113925d6882a7b.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Innovative', '/Assets/inspiration/Innovative/13ca1591ad8546a8810c6d65e90f73ed.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Innovative', '/Assets/inspiration/Innovative/IMG_0445.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Innovative', '/Assets/inspiration/Innovative/IMG_0444.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Innovative', '/Assets/inspiration/Innovative/IMG_0450.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Innovative', '/Assets/inspiration/Innovative/IMG_0440.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Innovative', '/Assets/inspiration/Innovative/IMG_0441.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Innovative', '/Assets/inspiration/Innovative/IMG_0442.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Innovative', '/Assets/inspiration/Innovative/a6308e6fc15875e248ebd5512a2eb6e4.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Innovative', '/Assets/inspiration/Innovative/IMG_0437.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Lifestyle', '/Assets/inspiration/Lifestyle/d19720319c846b30a81115d6d95ed4e6.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Lifestyle', '/Assets/inspiration/Lifestyle/WhatsApp Image 2026-05-11 at 10.24.54 PM.jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Lifestyle', '/Assets/inspiration/Lifestyle/bff9eba6720d9ee3461b39cd946e98fa.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Lifestyle', '/Assets/inspiration/Lifestyle/3c959653b46e14ce3130aed51a4d22db.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Lifestyle', '/Assets/inspiration/Lifestyle/WhatsApp Image 2026-05-11 at 10.05.05 PM (2).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Lifestyle', '/Assets/inspiration/Lifestyle/3166b4cf8cfc1fb3da9820ef6be719c1.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Lifestyle', '/Assets/inspiration/Lifestyle/141432b376294e697a08b3aaa47c1ce7.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Lifestyle', '/Assets/inspiration/Lifestyle/99677ffd7990f77b95435a1d2b9fd94e.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Lifestyle', '/Assets/inspiration/Lifestyle/209923844e374c575e20bf7455f3b290.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Lifestyle', '/Assets/inspiration/Lifestyle/WhatsApp Image 2026-05-11 at 10.24.54 PM (1).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Lifestyle', '/Assets/inspiration/Lifestyle/148e6ea2fba82405bb9f7a5d28b22046.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Lifestyle', '/Assets/inspiration/Lifestyle/WhatsApp Image 2026-05-11 at 10.05.06 PM.jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Lifestyle', '/Assets/inspiration/Lifestyle/803709fb411035f0e20c8f9dce79a1da.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Fashion', '/Assets/inspiration/Fashion/0f28e2c92d681d1bdcd491f06ed961b0.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Fashion', '/Assets/inspiration/Fashion/WhatsApp Image 2026-05-11 at 10.05.08 PM.jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Fashion', '/Assets/inspiration/Fashion/4f476fda531f141dc370c60f999dad6b.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Fashion', '/Assets/inspiration/Fashion/WhatsApp Image 2026-05-11 at 10.05.00 PM.jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Fashion', '/Assets/inspiration/Fashion/WhatsApp Image 2026-05-11 at 10.05.08 PM (1).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Fashion', '/Assets/inspiration/Fashion/WhatsApp Image 2026-05-11 at 10.05.04 PM (1).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Fashion', '/Assets/inspiration/Fashion/6fd075a4801a515c8d45058a261481fd.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Fashion', '/Assets/inspiration/Fashion/01a27e20d91fb7f6f0b99d1f86e30916.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Fashion', '/Assets/inspiration/Fashion/1ccbc4cc44467ee59f66df307327b916.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Fashion', '/Assets/inspiration/Fashion/aa1571bcb7412580c683c59d210127fa.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Fashion', '/Assets/inspiration/Fashion/26b08afa5900a656c387c32d7953bf1e.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Fashion', '/Assets/inspiration/Fashion/WhatsApp Image 2026-05-11 at 10.05.08 PM (2).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Fashion', '/Assets/inspiration/Fashion/61cc0002d8662bac2945ab6c1d286cc1.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Perfumes', '/Assets/inspiration/Perfumes/download (1).jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Perfumes', '/Assets/inspiration/Perfumes/Perfume Fino.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Perfumes', '/Assets/inspiration/Perfumes/download.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Perfumes', '/Assets/inspiration/Perfumes/Pin on small business plan _ Luxury packaging design, Perfume packaging, Cosmetic packaging design.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Perfumes', '/Assets/inspiration/Perfumes/WhatsApp Image 2026-05-11 at 10.04.54 PM (2).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Perfumes', '/Assets/inspiration/Perfumes/Illustrated packaging.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Perfumes', '/Assets/inspiration/Perfumes/Santo Wood Eau De Parfum.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Perfumes', '/Assets/inspiration/Perfumes/Lula.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Perfumes', '/Assets/inspiration/Perfumes/WhatsApp Image 2026-05-11 at 10.04.52 PM.jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Perfumes', '/Assets/inspiration/Perfumes/IMG_0418.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Perfumes', '/Assets/inspiration/Perfumes/Pure Sense.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Perfumes', '/Assets/inspiration/Perfumes/International Shipping.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Jewelry', '/Assets/inspiration/Jewelry/7d1bff129af1494e20f49fd99c7c8311.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Jewelry', '/Assets/inspiration/Jewelry/WhatsApp Image 2026-05-11 at 10.05.03 PM (2).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Jewelry', '/Assets/inspiration/Jewelry/WhatsApp Image 2026-05-11 at 10.05.03 PM.jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Jewelry', '/Assets/inspiration/Jewelry/80c314f33bfdd024a607114b7fd53428.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Jewelry', '/Assets/inspiration/Jewelry/b7fb40e30644cff2d6b8bdfa9611dddb.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Jewelry', '/Assets/inspiration/Jewelry/WhatsApp Image 2026-05-11 at 10.05.03 PM (1).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Jewelry', '/Assets/inspiration/Jewelry/WhatsApp Image 2026-05-11 at 10.05.05 PM.jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Jewelry', '/Assets/inspiration/Jewelry/578e5c506cf9466b4c56c38d223b4c26.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Jewelry', '/Assets/inspiration/Jewelry/WhatsApp Image 2026-05-11 at 10.05.02 PM (2).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Jewelry', '/Assets/inspiration/Jewelry/f5112956716e66d70448ab304b11c9c3.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Jewelry', '/Assets/inspiration/Jewelry/WhatsApp Image 2026-05-11 at 10.05.04 PM.jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Jewelry', '/Assets/inspiration/Jewelry/WhatsApp Image 2026-05-11 at 10.05.02 PM (1).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Jewelry', '/Assets/inspiration/Jewelry/WhatsApp Image 2026-05-11 at 10.05.02 PM (3).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Corporate Gifting', '/Assets/inspiration/Corporate Gifting/90d9c1a6d9b1f366492489b3972c99f7.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Corporate Gifting', '/Assets/inspiration/Corporate Gifting/77d5ff6d193b9f0310fe065e15b0edc0.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Corporate Gifting', '/Assets/inspiration/Corporate Gifting/IMG_0428.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Corporate Gifting', '/Assets/inspiration/Corporate Gifting/50ceb4998db975102c801061d2e389cf.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Corporate Gifting', '/Assets/inspiration/Corporate Gifting/846826e69a37244427c1db0ef6c4dc70.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Corporate Gifting', '/Assets/inspiration/Corporate Gifting/f1856915f41f2a9706e8b7ed195dd91e.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Corporate Gifting', '/Assets/inspiration/Corporate Gifting/994126ec350818f6e49b5b4b1bb29bf7.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Corporate Gifting', '/Assets/inspiration/Corporate Gifting/IMG_0425.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Corporate Gifting', '/Assets/inspiration/Corporate Gifting/IMG_0424.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Corporate Gifting', '/Assets/inspiration/Corporate Gifting/d1dc6b81b0cafee43d0b0cac21940b2c.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Corporate Gifting', '/Assets/inspiration/Corporate Gifting/IMG_0426.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Corporate Gifting', '/Assets/inspiration/Corporate Gifting/ab138c0796677dc963284f154ec1595d.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Corporate Gifting', '/Assets/inspiration/Corporate Gifting/IMG_0427.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Corporate Gifting', '/Assets/inspiration/Corporate Gifting/IMG_0423.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Corporate Gifting', '/Assets/inspiration/Corporate Gifting/IMG_0422.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Corporate Gifting', '/Assets/inspiration/Corporate Gifting/IMG_0420.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('PR', '/Assets/inspiration/PR/WhatsApp Image 2026-05-11 at 10.04.57 PM (1).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('PR', '/Assets/inspiration/PR/WhatsApp Image 2026-05-11 at 10.04.58 PM (2).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('PR', '/Assets/inspiration/PR/WhatsApp Image 2026-05-11 at 10.05.06 PM (2).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('PR', '/Assets/inspiration/PR/IMG_0429.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('PR', '/Assets/inspiration/PR/WhatsApp Image 2026-05-11 at 10.17.59 PM.jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('PR', '/Assets/inspiration/PR/WhatsApp Image 2026-05-11 at 10.04.57 PM (2).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('PR', '/Assets/inspiration/PR/WhatsApp Image 2026-05-11 at 10.05.06 PM (1).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('PR', '/Assets/inspiration/PR/WhatsApp Image 2026-05-11 at 10.04.54 PM.jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('PR', '/Assets/inspiration/PR/IMG_0431.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('PR', '/Assets/inspiration/PR/IMG_0430.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('PR', '/Assets/inspiration/PR/IMG_0432.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('PR', '/Assets/inspiration/PR/IMG_0433.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('PR', '/Assets/inspiration/PR/IMG_0436.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('PR', '/Assets/inspiration/PR/IMG_0434.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('PR', '/Assets/inspiration/PR/IMG_0435.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Industrial', '/Assets/inspiration/Industrial/7f987e304aacf054e8474c6fb77d579e.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Industrial', '/Assets/inspiration/Industrial/efe8ca429382c9889d5d5961283f1446.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Industrial', '/Assets/inspiration/Industrial/60732ed78077200ddb1c18e3cd792898.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Industrial', '/Assets/inspiration/Industrial/77e3c1d10b1302f5540fe6cf04823872.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Industrial', '/Assets/inspiration/Industrial/59ad3d7e1e84b38514d77290117ea2f6.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Industrial', '/Assets/inspiration/Industrial/99677ffd7990f77b95435a1d2b9fd94e.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Industrial', '/Assets/inspiration/Industrial/3e76c93f3089bfa4dd26555db4316ef9.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Industrial', '/Assets/inspiration/Industrial/13d5f592341c3464dd8809a210a7fdc7.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Industrial', '/Assets/inspiration/Industrial/bd94509d2f18dfeb39292edf98ef55b3.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Industrial', '/Assets/inspiration/Industrial/1ae55e1a4a4cc38fe3e87a704e1eace8.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Industrial', '/Assets/inspiration/Industrial/6a8cd0c88752841733fac48247eaad52.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Industrial', '/Assets/inspiration/Industrial/4fdf6c437156f3988cbbe4581a502824.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Industrial', '/Assets/inspiration/Industrial/43af6b9b1c7557ae2bde3a35b26fe2d6.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Industrial', '/Assets/inspiration/Industrial/7fd46f3652e31ebfedcf482ece8f9fd3.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Combo Packs', '/Assets/inspiration/Combo Packs/IMG_0458.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Combo Packs', '/Assets/inspiration/Combo Packs/IMG_0459.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Combo Packs', '/Assets/inspiration/Combo Packs/IMG_0461.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Combo Packs', '/Assets/inspiration/Combo Packs/IMG_0448.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Combo Packs', '/Assets/inspiration/Combo Packs/60435b57c517d1655d113925d6882a7b.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Combo Packs', '/Assets/inspiration/Combo Packs/IMG_0446.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Combo Packs', '/Assets/inspiration/Combo Packs/IMG_0453.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Combo Packs', '/Assets/inspiration/Combo Packs/IMG_0447.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Combo Packs', '/Assets/inspiration/Combo Packs/IMG_0444.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Combo Packs', '/Assets/inspiration/Combo Packs/IMG_0454.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Combo Packs', '/Assets/inspiration/Combo Packs/IMG_0455.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Combo Packs', '/Assets/inspiration/Combo Packs/IMG_0443.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Combo Packs', '/Assets/inspiration/Combo Packs/IMG_0457.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Combo Packs', '/Assets/inspiration/Combo Packs/IMG_0456.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Combo Packs', '/Assets/inspiration/Combo Packs/eb13cb86d8d8ef763a10b6f547206cfe.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Combo Packs', '/Assets/inspiration/Combo Packs/3fdc3d81486c587d4a3739c32e6562b7.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Beauty & Skincare', '/Assets/inspiration/Beauty & Skincare/25a052eb4abb967240889c695dd293dd.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Beauty & Skincare', '/Assets/inspiration/Beauty & Skincare/edc539286d1465ad7627fdbfa588355b.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Beauty & Skincare', '/Assets/inspiration/Beauty & Skincare/WhatsApp Image 2026-05-11 at 10.04.58 PM.jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Beauty & Skincare', '/Assets/inspiration/Beauty & Skincare/WhatsApp Image 2026-05-11 at 10.04.54 PM (2).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Beauty & Skincare', '/Assets/inspiration/Beauty & Skincare/WhatsApp Image 2026-05-11 at 10.04.58 PM (1).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Beauty & Skincare', '/Assets/inspiration/Beauty & Skincare/IMG_0449.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Beauty & Skincare', '/Assets/inspiration/Beauty & Skincare/IMG_0462.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Beauty & Skincare', '/Assets/inspiration/Beauty & Skincare/WhatsApp Image 2026-05-11 at 10.04.54 PM (1).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Beauty & Skincare', '/Assets/inspiration/Beauty & Skincare/IMG_0452.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Beauty & Skincare', '/Assets/inspiration/Beauty & Skincare/88222cabbc12e14bfab37e2092f530af.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Beauty & Skincare', '/Assets/inspiration/Beauty & Skincare/WhatsApp Image 2026-05-11 at 10.05.01 PM (1).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Beauty & Skincare', '/Assets/inspiration/Beauty & Skincare/IMG_0451.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Beauty & Skincare', '/Assets/inspiration/Beauty & Skincare/IMG_0455.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Beauty & Skincare', '/Assets/inspiration/Beauty & Skincare/bd94509d2f18dfeb39292edf98ef55b3.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Beauty & Skincare', '/Assets/inspiration/Beauty & Skincare/IMG_0457.JPG');
INSERT INTO public.inspirations (category, image_url) VALUES ('Beauty & Skincare', '/Assets/inspiration/Beauty & Skincare/c9cded6cdc82fdd155787c34535db0d6.jpg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Beauty & Skincare', '/Assets/inspiration/Beauty & Skincare/WhatsApp Image 2026-05-11 at 10.04.59 PM (1).jpeg');
INSERT INTO public.inspirations (category, image_url) VALUES ('Beauty & Skincare', '/Assets/inspiration/Beauty & Skincare/d7496605b46bb48600befcae62b78cdf.jpg');
